name: Build JS Bundles

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: node build.js
      - name: Upload bundles
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs
          retention-days: 1
